### ISSUE TITLE
SQLite option

### ISSUE THREAD

**Issue by JacKeTUs** [Spacefreak18/simmonitor#1]
Hi, quick question:
Is there any specific reason, why you're using PostgreSQL on that?
I think that small SQLite will do just fine by default, and there is function already for it in Hoel: https://babelouest.github.io/hoel/group__init.html#ga8d57dba0fe4db20b82f7e093bb15a33f

**Comment by Spacefreak18** [comment]
no real reason, other than i thought it would be nice to have a common place to store and share sessions for possible comparison of different driver times.

For example, in the config i have checked in, is a hosted version of PSQL. It's hosted for free on elephant sql until the end of the year.

**Comment by JacKeTUs** [comment]
Share sessions between different players is nice tho
Like, everybody can send info to your(?) server (or may be tournament organisers in far future lol)
But how convenient it would be for newcomers and preferably offline players? Like, i dont need PSQL to drive in ETS...
